# Generated by Django 5.0.7 on 2025-09-01 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fixed_speed_camera', 'Fixed Speed Camera'), ('mobile_tripod', 'Mobile Speed Camera'), ('red_light', 'Red Light Camera'), ('average_speed', 'Average Speed Camera'), ('section_control', 'Section Control'), ('bus_lane', 'Bus Lane Camera'), ('other', 'Other')], default='fixed_speed_camera', max_length=32)),
                ('sector_json', models.JSONField(help_text='Detection area polygon as GeoJSON')),
                ('center_lat', models.FloatField(help_text='Center latitude')),
                ('center_lon', models.FloatField(help_text='Center longitude')),
                ('speed_limit', models.IntegerField(blank=True, help_text='Speed limit in km/h', null=True)),
                ('direction', models.CharField(blank=True, choices=[('both', 'Both Directions'), ('north', 'Northbound'), ('south', 'Southbound'), ('east', 'Eastbound'), ('west', 'Westbound')], default='both', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this radar')),
                ('verified', models.BooleanField(default=False, help_text='Whether this radar has been verified')),
                ('active', models.BooleanField(default=True, help_text='Whether this radar is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('alert_count', models.PositiveIntegerField(default=0, help_text='Number of times this radar has been detected')),
                ('last_detected', models.DateTimeField(blank=True, help_text='Last time this radar was detected', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this radar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_radars', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who verified this radar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_radars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Anonymous device identifier', max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField(blank=True, help_text='Vehicle speed in km/h if available', null=True)),
                ('location_lat', models.FloatField(blank=True, help_text='Detection location latitude', null=True)),
                ('location_lon', models.FloatField(blank=True, help_text='Detection location longitude', null=True)),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='radars.radar')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RadarReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_device', models.CharField(help_text='Anonymous device identifier', max_length=100)),
                ('location_lat', models.FloatField(help_text='Report location latitude')),
                ('location_lon', models.FloatField(help_text='Report location longitude')),
                ('report_type', models.CharField(choices=[('confirmed', 'Confirmed Active'), ('inactive', 'Not Active'), ('moved', 'Moved Location'), ('false_positive', 'False Detection'), ('new_radar', 'New Radar Spotted')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from reporter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('radar', models.ForeignKey(blank=True, help_text='Radar being reported (null for new radar reports)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='radars.radar')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='radar',
            index=models.Index(fields=['type'], name='radars_rada_type_68cbfa_idx'),
        ),
        migrations.AddIndex(
            model_name='radar',
            index=models.Index(fields=['verified'], name='radars_rada_verifie_eb0a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='radar',
            index=models.Index(fields=['active'], name='radars_rada_active_5499e9_idx'),
        ),
        migrations.AddIndex(
            model_name='radar',
            index=models.Index(fields=['created_at'], name='radars_rada_created_219527_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['radar', 'detected_at'], name='radars_dete_radar_i_957e59_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['detected_at'], name='radars_dete_detecte_2e2b26_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['device_id', 'detected_at'], name='radars_dete_device__9719d0_idx'),
        ),
        migrations.AddIndex(
            model_name='radarreport',
            index=models.Index(fields=['report_type'], name='radars_rada_report__040589_idx'),
        ),
        migrations.AddIndex(
            model_name='radarreport',
            index=models.Index(fields=['created_at'], name='radars_rada_created_2006ac_idx'),
        ),
        migrations.AddIndex(
            model_name='radarreport',
            index=models.Index(fields=['radar', 'report_type'], name='radars_rada_radar_i_bc24c3_idx'),
        ),
    ]
