# Generated by Django 5.0.7 on 2025-09-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0001_initial'),
    ]

    operations = [
        # Remove the direction field from Radar model
        migrations.RemoveField(
            model_name='radar',
            name='direction',
        ),
    ]
