# Generated by Codex CLI on migration addition

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0002_auto_20250902_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=50, unique=True, help_text='Stable code identifier (e.g. speed_control)')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100, help_text='Optional grouping label (e.g. Stationary hazards)')),
                ('color', models.CharField(default='#2ECC71', max_length=9, help_text='Hex color, e.g. #2ECC71')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name_plural': 'Radar categories',
            },
        ),
        migrations.AddField(
            model_name='radar',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radars', to='radars.radarcategory'),
        ),
        migrations.AddField(
            model_name='radar',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='radar_icons/'),
        ),
        migrations.AddField(
            model_name='radar',
            name='icon_color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddIndex(
            model_name='radar',
            index=models.Index(fields=['category'], name='radars_rada_category_idx'),
        ),
        migrations.AddIndex(
            model_name='radarcategory',
            index=models.Index(fields=['code'], name='radars_rada_code_idx'),
        ),
        migrations.AddIndex(
            model_name='radarcategory',
            index=models.Index(fields=['is_active'], name='radars_rada_is_acti_idx'),
        ),
    ]

