# Generated by Django 5.0.7 on 2025-09-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0003_radarcategory_and_presentation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='radar',
            new_name='radars_rada_categor_37a934_idx',
            old_name='radars_rada_category_idx',
        ),
        migrations.RenameIndex(
            model_name='radarcategory',
            new_name='radars_rada_code_909ca1_idx',
            old_name='radars_rada_code_idx',
        ),
        migrations.RenameIndex(
            model_name='radarcategory',
            new_name='radars_rada_is_acti_e461c4_idx',
            old_name='radars_rada_is_acti_idx',
        ),
        migrations.AlterField(
            model_name='radar',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional icon overriding category icon', null=True, upload_to='radar_icons/'),
        ),
        migrations.AlterField(
            model_name='radar',
            name='icon_color',
            field=models.CharField(blank=True, help_text='Optional hex color overriding category color', max_length=9, null=True),
        ),
    ]
