# Generated by Codex CLI to switch RadarCategory.group -> groups(JSON)

from django.db import migrations, models
from django.utils.text import slugify


def migrate_groups(apps, schema_editor):
    RadarCategory = apps.get_model('radars', 'RadarCategory')
    for rc in RadarCategory.objects.all():
        # If 'group' attribute still exists in the historical model
        g = getattr(rc, 'group', '') if hasattr(rc, 'group') else ''
        if isinstance(g, str) and g.strip():
            key_map = {
                'Stationary hazards': 'stationary',
                'Safe cameras': 'safe',
                'Popular places of hazards': 'popular',
                'Other': 'other',
            }
            key = key_map.get(g.strip(), slugify(g.strip()))
            try:
                rc.groups = [key]
            except Exception:
                rc.groups = []
        else:
            rc.groups = []
        rc.save(update_fields=['groups'])


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0003_radarcategory_and_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarcategory',
            name='groups',
            field=models.JSONField(default=list, help_text='List of group keys (strings)'),
        ),
        migrations.RunPython(migrate_groups, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='radarcategory',
            name='group',
        ),
    ]
