# Generated by Django 5.0.7 on 2025-09-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0004_category_groups_replace_group'),
        ('radars', '0004_rename_radars_rada_category_idx_radars_rada_categor_37a934_idx_and_more'),
    ]

    operations = [
    ]
