# Generated by Codex CLI to drop Radar.type

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0004_category_groups_replace_group'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='radar',
            name='radars_rada_type_68cbfa_idx',
        ),
        migrations.RemoveField(
            model_name='radar',
            name='type',
        ),
    ]

