# Generated by Codex CLI to set default category for existing radars

from django.db import migrations


def set_default_category(apps, schema_editor):
    Radar = apps.get_model('radars', 'Radar')
    RadarCategory = apps.get_model('radars', 'RadarCategory')
    # Ensure default category exists
    cat, _ = RadarCategory.objects.get_or_create(
        code='default_camera',
        defaults={
            'name': 'Default camera',
            'groups': ['other'],
            'color': '#2ECC71',
            'order': 100,
            'is_active': True,
        }
    )
    # Assign to any Radar without category
    Radar.objects.filter(category__isnull=True).update(category=cat)


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0005_remove_radar_type'),
    ]

    operations = [
        migrations.RunPython(set_default_category, migrations.RunPython.noop),
    ]

