# Generated by Django 5.0.7 on 2025-09-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0005_merge_20250905_0631'),
        ('radars', '0005_remove_radar_type'),
    ]

    operations = [
    ]
