# Generated by Django 5.0.7 on 2025-09-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0006_merge_0005_merge_20250905_0631_0005_remove_radar_type'),
        ('radars', '0006_set_default_category'),
    ]

    operations = [
    ]
