name: mobile_radar
description: Mobile Radar – Flutter client
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.5.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  sqflite: ^2.4.2
  path: ^1.9.0
  path_provider: ^2.1.5
  maplibre_gl: ^0.22.0
  geolocator: ^14.0.2
  audioplayers: ^6.0.0
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sounds/
